const ACCOUNT = {
  GET_GIVEN_OFFERS_SUCCESS: "GET_GIVEN_OFFERS_SUCCESS",
  GET_GIVEN_OFFERS_ERROR: "GET_GIVEN_OFFERS_ERROR",
  GET_RECEIVED_OFFERS_SUCCESS: "GET_RECEIVED_OFFERS_SUCCESS",
  GET_RECEIVED_OFFERS_ERROR: "GET_RECEIVED_OFFERS_ERROR",
  REJECT_OFFER_SUCCESS: "REJECT_OFFER_SUCCESS",
  REJECT_OFFER_ERROR: "REJECT_OFFER_ERROR",
  ACCEPT_OFFER_SUCCESS: "ACCEPT_OFFER_SUCCESS",
  ACCEPT_OFFER_ERROR: "ACCEPT_OFFER_ERROR",
  CANCEL_OFFER_SUCCESS: "CANCEL_OFFER_SUCCESS",
  CANCEL_OFFER_ERROR: "CANCEL_OFFER_ERROR",
};

export default ACCOUNT;
