const BRANDS = {
  GET_ALL_BRANDS_SUCCESS: "GET_ALL_BRANDS_SUCCESS",
  GET_ALL_BRANDS_ERROR: "GET_ALL_BRANDS_ERROR",
  GET_BRAND_BY_ID_SUCCESS: "GET_BRAND_BY_ID_SUCCESS",
  GET_BRAND_BY_ID_ERROR: "GET_BRAND_BY_ID_ERROR",
};

export default BRANDS;
