const CATEGORIES = {
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_ERROR: "GET_ALL_CATEGORIES_ERROR",
  GET_CATEGORY_BY_ID_SUCCESS: "GET_CATEGORY_BY_ID_SUCCESS",
  GET_CATEGORY_BY_ID_ERROR: "GET_CATEGORY_BY_ID_ERROR",
};

export default CATEGORIES;
