const COLORS = {
  GET_ALL_COLORS_SUCCESS: "GET_ALL_COLORS_SUCCESS",
  GET_ALL_COLORS_ERROR: "GET_ALL_COLORS_ERROR",
  GET_COLOR_BY_ID_SUCCESS: "GET_COLOR_BY_ID_SUCCESS",
  GET_COLOR_BY_ID_ERROR: "GET_COLOR_BY_ID_ERROR",
};

export default COLORS;
