const FILE = {
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_ERROR: "UPLOAD_FILE_ERROR",
  UPLOADING_PROGRESS: "UPLOADING_PROGRESS",
  RESET_PRODUCT_IMAGE_URL: "RESET_PRODUCT_IMAGE_URL",
};

export default FILE;
