const PRODUCTS = {
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  IS_LOADING_PRODUCTS: "IS_LOADING_PRODUCTS",
  GET_ALL_PRODUCTS_ERROR: "GET_ALL_PRODUCTS_ERROR",
  GET_PRODUCTS_BY_CATEGORY: "GET_PRODUCTS_BY_CATEGORY",
  GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
  GET_PRODUCT_BY_ID_ERROR: "GET_PRODUCT_BY_ID_ERROR",
  PURCHASE_PRODUCT_BY_ID_SUCCESS: "PURCHASE_PRODUCT_BY_ID_SUCCESS",
  PURCHASE_PRODUCT_BY_ID_ERROR: "PURCHASE_PRODUCT_BY_ID_ERROR",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_ERROR: "ADD_PRODUCT_ERROR",
  OFFER_PRODUCT_SUCCESS: "OFFER_PRODUCT_SUCCESS",
  OFFER_PRODUCT_ERROR: "OFFER_PRODUCT_ERROR",
  IS_LOADING_PRODUCT: "IS_LOADING_PRODUCT",
};

export default PRODUCTS;
