const STATUS = {
  GET_ALL_STATUS_SUCCESS: "GET_ALL_STATUS_SUCCESS",
  GET_ALL_STATUS_ERROR: "GET_ALL_STATUS_ERROR",
  GET_STATUS_BY_ID_SUCCESS: "GET_STATUS_BY_ID_SUCCESS",
  GET_STATUS_BY_ID_ERROR: "GET_STATUS_BY_ID_ERROR",
};

export default STATUS;
